spring:
  application:
    name: university
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: university
    password: university
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080